name: Comprobar Tokens

on:
  push:
    branches: [ "**" ]

jobs:
  verificar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: bash
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
          LOCAL_DEV: ${{ env.LOCAL_DEV_TOKEN }}
        run: |
          if [ "$SECRET_DEV" = "$LOCAL_DEV" ]; then
            echo "¡Coinciden! El token local es correcto."
            exit 0
          else
            echo "ERROR: Los tokens no coinciden."
            exit 1
          fi