name: Comprobar Tokens

on:
  push:
    branches: [ "**" ]

jobs:
  verificar-tokens:
    runs-on: self-hosted
    steps:
      - name: Comparar DEV_TOKEN con LOCAL_DEV_TOKEN
        shell: cmd
        env:
          SECRET_DEV: ${{ secrets.DEV_TOKEN }}
          LOCAL_DEV: "12345"
        run: |
          if "%SECRET_DEV%"=="%LOCAL_DEV%" (
              echo Coinciden! El token es correcto.
              exit /b 0
          ) else (
              echo ERROR: Los tokens no coinciden.
              exit /b 1
          )